name: genre_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip==23.2.1
  - pip:
      - requests==2.24.0
      - mlflow==2.10.2
      - hydra-core==1.3.2
      - wandb==0.16.3
      - hydra-joblib-launcher==1.2.0
