name: check_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip==23.2.1
  - pip:
    - wandb==0.16.3
    - numpy==1.24.4
    - pandas==2.0.3
    - pytest==7.4.0
    - scipy==1.10.1
