name: evaluate_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip==23.2.1
  - pip:
    - wandb==0.16.3
    - pandas==2.0.3
    - scikit-learn==1.3.0
    - matplotlib==3.7.2
    - plotly==4.4.1
    - pillow==8.1.2
    - mlflow==2.10.2
